**Question 1 -Write a Python Program to Add Two Matrices?**


**Answer 1 -**

In [1]:
import numpy as np

X = [[1,2,3],	[1,2,3],[1,2,3]]

Y = [[1,2,3], [1,2,3], [1,2,3]]

result = np.array(X) + np.array(Y)

print(result)

[[2 4 6]
 [2 4 6]
 [2 4 6]]


**##########################################################################################################**

**Question 2 -Write a Python Program to Multiply Two Matrices?**


**Answer 2 -**

In [2]:
A = [[1,2,3],	[1,2,3],[1,2,3]]

# take a 3x3 matrix
B = [[1,2,3],	[1,2,3],[1,2,3]]

# result will be 3x4

result= [[0,0,0],
		[0,0,0],
		[0,0,0]]

result = np.dot(A,B)
print("Multiplication of Matrix A and Matrix B is  = ", end=" ")
for r in result:
	print(r)

Multiplication of Matrix A and Matrix B is  =  [ 6 12 18]
[ 6 12 18]
[ 6 12 18]


**##########################################################################################################**

**Question 3 -Write a Python Program to Transpose a Matrix?**


**Answer 3 -**

In [4]:
n = 3


def trans(M):
  for i in range(n):
    for j in range(i+1, n):
     M[i][j],M[j][i] =M[j][i],M[i][j]




# driver code
M = [ [1, 1, 1],
[2, 2, 2],
[3, 3, 3],
[4, 4, 4]]

trans(M)

print("Modified matrix is")
for i in range(n):
  for j in range(n):
    print(M[i][j], " ", end='')
  print()

Modified matrix is
1  2  3  
1  2  3  
1  2  3  


**##########################################################################################################**

**Question 4 -Write a Python Program to Sort Words in Alphabetic Order?**


**Answer 4 -**

In [6]:
def sort(Str):
	words = Str.split(" ")
	for i in range(len(words)):
		words[i] = words[i].lower()
	words.sort()

	# return the sorted words
	return ' '.join(words)

# Driver code
Str = "Python Program to Sort Words in Alphabetic Order"
print(sort(Str))

alphabetic in order program python sort to words


**##########################################################################################################**

**Question 5 -Write a Python Program to Remove Punctuation From a String?**


**Answer 5 -**

In [9]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

str = "Question 5 -Write a Python Program to Remove Punctuation From a String? Answer 5 -"

new_str = ""
for char in str:
   if char not in punctuations:
       new_str = new_str + char


print(new_str)

Question 5 Write a Python Program to Remove Punctuation From a String Answer 5 


**##########################################################################################################**